---
abstract: 'Thesaurus management'
author:
  - 'Laurent Dami <dami@cpan.org>'
build_requires:
  Test::More: '0'
configure_requires:
  Module::Build: '0'
dynamic_config: 1
generated_by: 'Module::Build version 0.4205, CPAN::Meta::Converter version 2.133380'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: Lingua-Thesaurus
provides:
  Lingua::Thesaurus:
    file: lib/Lingua/Thesaurus.pm
    version: '0.09'
  Lingua::Thesaurus::IO:
    file: lib/Lingua/Thesaurus/IO.pm
  Lingua::Thesaurus::IO::ISO2788:
    file: lib/Lingua/Thesaurus/IO/ISO2788.pm
  Lingua::Thesaurus::IO::Jurivoc:
    file: lib/Lingua/Thesaurus/IO/Jurivoc.pm
  Lingua::Thesaurus::IO::LivelinkCollectionServer:
    file: lib/Lingua/Thesaurus/IO/LivelinkCollectionServer.pm
  Lingua::Thesaurus::RelType:
    file: lib/Lingua/Thesaurus/RelType.pm
  Lingua::Thesaurus::Storage:
    file: lib/Lingua/Thesaurus/Storage.pm
  Lingua::Thesaurus::Storage::SQLite:
    file: lib/Lingua/Thesaurus/Storage/SQLite.pm
  Lingua::Thesaurus::Term:
    file: lib/Lingua/Thesaurus/Term.pm
requires:
  Carp: '0'
  DBD::SQLite: '1.39'
  DBI: '0'
  Module::Load: '0'
  Moose: '0'
  Search::Tokenizer: '0'
  namespace::clean: '0'
  perl: '5.01'
resources:
  license: http://dev.perl.org/licenses/
  repository: https://github.com/damil/Lingua-Thesaurus
version: '0.09'
